# Chapter 2.1. 선형방정식 및 선형시스템
* 선형방정식(Linear Equation)과 선형시스템(Linear System)
* 단위행렬(Identity Matrix)와 역행렬(Inverse Matrix)

In [2]:
import numpy as np

## 2.1.1.  선형방정식(Linear Equation)
* $x_1, x_2, \cdots, x_n$을 변수로 가진 선형방정식은 다음과 같은 형태로 나타냄 $$ a_1x_1 + a_2x_2 + \cdots + a_nx_n = b$$
$b$ 와 coefficients $a_1, a_2, \cdots, a_n$는 실수 혹은 복소수
* 위의 방정식은 다음과 같이 나타낼 수 있음  
$$\mathbf{a}^T\mathbf{x} = \mathbf{b}$$  
$$where,\mathbf{a} = \begin{bmatrix} a_1 \\ a_2 \\ \vdots \\ a_n \end{bmatrix}, \mathbf{x} = \begin{bmatrix} x_1 \\ x_2 \\ \vdots \\ x_n \end{bmatrix}.$$

## 2.1.2. 선형시스템(Linear System)
* 선형시스템은 선형방정식들의 집합(연립방정식)
* 선형시스템의 예 :
    
    
    1. 데이터    
PearsonID | Weight | Height | Is_smoking | Life-span
----------|--------|--------|------------|----------
1         |60kg    |5.5ft   |Yes (=1)    |66
2         |65kg    |5.0ft   |No (=0)     |74
3         |55kg    |6.0ft   |Yes (=1)    |78  

    2. 선형 시스템 set up
$$60x_1 + 5.5x_2 + 1 \cdot x_3 = 66$$ $$65x_1 + 5.0x_2 + 0 \cdot x_3 = 74$$ $$55x_1 + 6.0x_2 + 1 \cdot x_3 = 78$$

    3. 선형 시스템의  모든 coefficients를 matrix로 구성
$$\mathbf{A} = \begin{bmatrix} 60 & 5.5 & 1 \\ 65 & 5.0 & 0 \\ 55 & 6.0 & 1 \end{bmatrix}$$

    4. 타겟 vector와 가중치 vector 구성
$$\mathbf{x} = \begin{bmatrix} x_1 \\ x_2 \\ x_3 \end{bmatrix}, \mathbf{b} = \begin{bmatrix} 66 \\ 74 \\ 78 \end{bmatrix}$$

    5. 하나의 matrix equation으로 변환
$$\begin{bmatrix} 60 & 5.5 & 1 \\ 65 & 5.0 & 0 \\ 55 & 6.0 & 1 \end{bmatrix}\begin{bmatrix} x_1 \\ x_2 \\ x_3 \end{bmatrix} = \begin{bmatrix} 66 \\ 74 \\ 78 \end{bmatrix}$$
$$\mathbf{A} \mathbf{x} = \mathbf{b}$$


## 2.1.3. 단위행렬/항등행렬(Identity Matrix)
* 주대각선이 전부 1이고 나머지 요소는 0을 값으로 갖는 $n \times n$ 정방행렬(square matrix), $I_n = \mathbb{R}^n$
* e.g., $ I_3 = \begin{bmatrix} 1 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 1 \end{bmatrix}$
* $AI_n = I_nA = A$

In [3]:
print(np.identity(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## 2.1.4. 역행렬(Inverse Matrix)
* 정방행렬(square matrix) $A \in \mathbb{R}^{n\times n}$에 대하여, 역행렬 $A^{-1}$은 다음과 같이 정의됨
$$A^{-1}A = AA^{-1} = I_n$$
* $2 \times 2$ 행렬 $A = \begin{bmatrix} a & b \\ c & d \end{bmatrix}$에 대하여, 역행렬 $A^{-1}$은
$$A^{-1} = \frac{1}{ad-bc} \begin{bmatrix} d & -b \\ -c & a \end{bmatrix}$$
* $A \in \mathbb{R}^{n\times n}$ where $n >= 3$의 역행렬은 가우스 소거법(Gaussian elimination)을 이용해 계산

In [3]:
A = np.array([[2,3,-2], [3,5,6], [2,4,3]])
print(np.linalg.inv(A))

[[ 0.69230769  1.30769231 -2.15384615]
 [-0.23076923 -0.76923077  1.38461538]
 [-0.15384615  0.15384615 -0.07692308]]


## 2.1.5. 역행렬을 이용한 선형시스템 해 도출
$$\mathbf{A}\mathbf{x} = \mathbf{b}$$
$$\mathbf{A}^{-1}\mathbf{A}\mathbf{x} = \mathbf{A}^{-1}\mathbf{b}$$
$$I_n\mathbf{x} = \mathbf{A}^{-1}\mathbf{b}$$
$$\mathbf{x} = \mathbf{A}^{-1}\mathbf{b}$$

In [4]:
A = np.array([[2,3,-2], [3,5,6], [2,4,3]])
b = np.array([[-5], [12], [7]])
Ainv = np.linalg.inv(A)
x = np.dot(Ainv, b)
print(x)

[[-2.84615385]
 [ 1.61538462]
 [ 2.07692308]]


In [5]:
print(np.linalg.solve(A, b))

[[-2.84615385]
 [ 1.61538462]
 [ 2.07692308]]


## 2.1.6. 역행렬이 존재하지 않는 경우
* $A$의 역행렬이 존재하는 경우($A$가 가역행렬(invertible matrix))
    * 해(solution)은 $\mathbf{x} = \mathbf{A}^{-1}\mathbf{b}$로 유일하게 존재

* $A$의 역행렬이 존재하지 않는 경우($A$가 특이행렬(singular matrix))
    * $det A = 0(det A = ad-bc, A \in \mathbb{R}^{2\times2})$인 경우, $A$의 역행렬이 존재하지 않음
    * $det A = 0$이면, $\mathbf{A}\mathbf{x} = \mathbf{b}$의 해가 무수히 많거나(infinitely many solutions) 해가 없음(no solution)
    

## 2.1.7. Rectangular Matrix의 경우
* $A \in \mathbb{R}^{m \times n}$, $m < n$ : variables이 equations보다 많은 경우, 일반적으로 해가 무수히 많음(under-determined system)
* $A \in \mathbb{R}^{m \times n}$, $m > n$ : variables이 equations보다 적은 경우, 일반적으로 해가 없음(over-determined system)
* 가장 근사적으로 만족시키는 해를 구하는 것은 가능(e.g. regularization, least squares)